let words = [
  "salom",
  "Yaxshi boring",
  "Yaxshi qoling",
  "tulki",
  "narvon",
  "bosh kiyim",
  "sharbat",
  "radio",
  "banan",
  "ona",
  "daraxt",
  "ota",
  "go'sht",
  "sosiska",
  "kofe",
  "uzum",
  "quyon",
  "abadok",
  "o'pich",
  "yubka",
  "pomidor",
  "dum",
  "o'yinchoq",
  "sho'rva",
  "kamera",
  "stul",
  "narda toshi",
  "tort",
  "cho'chqa",
  "shirinlik",
  "it",
  "soat",
  "sviter",
  "dush",
  "ot",
  "tog'",
  "do'st",
  "to'p",
  "osmon",
  "bulut",
  "ko'zoynak",
  "picture",
  "sumka",
  "suv idish",
  "non",
  "qor, ko'z",
  "ayiq",
  "oy",
  "oshxona",
  "fartuk",
  "gul",
  "taroq",
  "uy",
  "baliq ovi",
  "stakan",
  "ovqat",
  "kiyim",
  "lupa",
  "kitob",
  "o'rmon",
  "maktab",
  "outfield",
  "bor",
  "kunduzi",
  "oldi taraf",
  "dori",
  "Nice to meet you!",
  "What's your name?",
  "Korea",
  "Germany",
  "USA",
  "Brazil",
  "England",
  "Japan",
  "China",
  "France",
  "Australia",
  "Where are you from?",
  "Bobo",
  "Buvi",
  "opa bolalar uchun",
  "aka bolalar uchun",
  "opa qizlar uchun",
  "aka qizlar uchun",
  "singil",
  "uka",
  "biz",
  "kim",
  "yes",
  "no",
  "Mongolia",
  "Russia",
  "madaniyat",
  "xursand bo'lmoq",
  "chet el",
  "chet ellik",
  "Indoneziya",
  "uzr so'ramoq",
  "oila",
  "erkak",
  "qiz farzand",
  "aktyor",
  "ha (javobda)",
  "apelsin",
  "Inchon sh.",
  "Seul",
  "uy bekasi",
  "kasb",
  "xodim",
  "uzum",
  "u (narsa)",
  "hola (begonaga nisbatan)",
  "qaysi",
  "bu yer",
  "bir qancha",
  "kalit",
  "salomlashuv",
  "ana u",
  "ana u yer(da)",
  "ana u tomon",
  "deraza",
  "qiziqish, yoqtirgan mashg'ulot",
  "do'stlashmoq, yaqin bo'lib ketmoq",
  "Tailand",
  "koreys milliy kiyimi",
  "sumka",
  "xil",
  "kuchukcha",
  "dona (narsalar uchun)",
  "narsa",
  "to'p",
  "daftar",
  "kitobni sanash so'zi",
  "Namsan tog'i",
  "muzlatgich",
  "elchixona",
  "lupa",
  "orqa, orqasi",
  "narsa, mahsulot",
  "olma",
  "o'rasida",
  "dars",
  "yondaftar",
  "soat",
  "past, pastga",
  "ko'zoynak",
  "old (tomon, taraf)",
  "dorixona",
  "yo'q bo'lmoq",
  "yon (tomon)",
  "o'ng tomon",
  "chap tomon",
  "pochta",
  "marka",
  "ust, yuqori",
  "bank",
  "bu tomon",
  "internet",
  "bor bo'lmoq",
  "o'chirg'ich",
  "kitob",
  "parta, stol",
  "doska",
  "yotoq, karavot",
  "kompyuter",
  "televizor",
  "do'kon with P",
  "penal",
  "narx",
  "tamaddi",
  "birga",
  "osmoq, ilmoq",
  "sen",
  "yangiliklar",
  "suhbat",
  "bermoq (hurmat shakli)",
  "eshitmoq",
  "tayyorlamoq",
  "ko'p",
  "qilmaslik, bajarmaslik",
  "yemoq",
  "suv",
  "nimani (qasqartirilgan variant)",
  "olmoq",
  "xona",
  "o'rganmoq",
  "ko'rmoq",
  "oshxona (uy ichidagi)",
  "olov",
  "non",
  "sevgi, muhabbat",
  "yozmoq",
  "qo'shimcha ish",
  "ingliz tili",
  "kino",
  "chet tili",
  "taom",
  "sport (bilan shug'ullanmoq)",
  "ichimlik",
  "kiymoq",
  "qo'ng'iroq qilmoq",
  "uy telefoni",
  "hozir",
  "uy",
  "qahva",
  "tort",
  "kola",
  "qilmoq",
  "raqam",
  "mebel",
  "o'rta",
  "mehmonlar uchun xona",
  "o'qish (ta'lim olmoq)",
  "sinf xonasi",
  "toza",
  "daraxt",
  "keng",
  "qo'ymoq (ichiga)",
  "pul",
  "~dan ko'ra",
  "odatda",
  "ruchka",
  "tez-tez",
  "stakan yoki stakanni sanash so'zi",
  "joy",
  "avtobus bekati",
  "xizmatchi",
  "qavat",
  "koreys tili",
  "do'kon",
  "bormoq",
  "joy with K",
  "aeroport",
  "u tomon",
  "teatr",
  "yotoqxona",
  "yopmoq",
  "kutubxona",
  "Dondemun",
  "kirib bormoq",
  "go'zallik saloni",
  "tag",
  "tun",
  "shifoxona; kasalxona",
  "idora, ofis",
  "kitob do'koni",
  "kvartira",
  "qayerda, qayerga",
  "allo",
  "bolalar bog'chasi",
  "qahvaxona (yaxshi ma'noda)",
  "taksi",
  "terminal",
  "ishdan uyga qaytmoq",
  "qo'l",
  "pansionat",
  "maktab",
  "talabalik guvohnomasi",
  "hojatxona",
  "firma (ish joyi ham nazarda tutiladi)",
  "o'rgatmoq",
  "narx",
  "bog'",
  "rasm chizmoq",
  "rasm",
  "yozuv",
  "Namdemun",
  "attraktsion",
  "basketbol (o'ynamoq)",
  "yugurish",
  "tamaki",
  "banan",
  "o'rganmoq",
  "Vetnam",
  "ko'rmoq",
  "qarzga olmoq",
  "lug'at",
  "tushuntirish",
  "supermarket",
  "oshxona",
  "oyoq kiyimi",
  "amaki (begonalarga nisbatan)",
  "~mayman, ~maymiz",
  "beysbol (o'ynamoq)",
  "dori",
  "sport maydoni",
  "yoqtirmoq, yaxshi ko'rmoq",
  "arqonda sakrash",
  "sport zali",
  "futbol (o'ynamoq)",
  "do'st",
  "sotmoq",
  "shunday (javobda, qisqartirilgan shaklda)",
  "shunday (tuslanmagan shaklda)",
  "Nengmyon (sovuq shaklda tortiladigan koreys taom",
  "suzish (suzmoq)",
  "muzqaymoq",
  "juda",
  "hali",
  "qalam",
  "yemoq (hurmat shakli)",
  "tinch",
  "karmon",
  "shokolad",
  "raqsga tushmoq",
  "chekmoq",
  "yo'l",
  "nima",
  "mashq (qilmoq)",
  "asosan",
  "ho'jayin (egalik nazarda tutilyapti)",
  "hafta",
  "asta-sekin",
  "qo'shiqchi",
  "qorni och bo'lmoq",
  "tufli",
  "quloq",
  "kutmoq",
  "kayfiyat",
  "past, pakana",
  "juda",
  "ha (javobda)",
  "baland",
  "hamma, hammasi",
  "hayvonlarni sanash uchun sanoq so'zi",
  "ko'p",
  "tomoq",
  "kechirim",
  "oyoq",
  "ta'til",
  "avtobus",
  "Pusan sh.",
  "qimmat",
  "samolyot",
  "tez",
  "yosh",
  "yashamoq",
  "suzish havzasi",
  "dam olmoq",
  "chang'i",
  "bozor",
  "oyoq kiyim kiymoq",
  "arzon",
  "og'rimoq",
  "bilmoq",
  "astoydil",
  "kinoteatr",
  "aktyor; aktrisa",
  "chiroyli",
  "ellik raqami",
  "krossovka, sport poyafzali",
  "musiqa",
  "shifokor",
  "og'iz",
  "yengil mashina",
  "o'tgan yil",
  "kichkina",
  "kam",
  "rost, haqiqatdan ham",
  "rostdan",
  "ming",
  "tozalov",
  "burun",
  "katta",
  "tennis",
  "futbolka",
  "pianino",
];

document.querySelector("button").addEventListener("click", () => {
  word = words[Math.floor(Math.random() * words.length)];
  document.querySelector("h1").innerHTML = word;
  words.splice(words.indexOf(`${word}`), 1);
  console.log(words);
});
